######################################################################
##
## Filename: lab1tb.udo
## Created on: Wed Jan 24 09:59:05 PM EST 2018
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
