######################################################################
##
## Filename: lab1tb.udo
## Created on: Thu Jan 25 6:04:31 PM Eastern Standard Time 2018
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
