######################################################################
##
## Filename: ut_multiplier.udo
## Created on: Tue Mar 06 4:49:46 PM Eastern Standard Time 2018
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
